# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='client',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63lient.proto\x12\x06\x63lient\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x07Request\x12\x14\n\x0c\x63lient_token\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x14\n\x0crequest_data\x18\x03 \x01(\x0c\"!\n\x08Response\x12\x15\n\rresponse_data\x18\x01 \x01(\t\"\x14\n\x12UpFilesListRequest\"$\n\x16UpFilesRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xa3\x02\n\x11UpFilesController\x12\x38\n\x04List\x12\x1a.client.UpFilesListRequest\x1a\x10.client.Response\"\x00\x30\x01\x12/\n\x06\x43reate\x12\x0f.client.Request\x1a\x10.client.Response(\x01\x30\x01\x12>\n\x08Retrieve\x12\x1e.client.UpFilesRetrieveRequest\x1a\x10.client.Response\"\x00\x12-\n\x06Update\x12\x0f.client.Request\x1a\x10.client.Response\"\x00\x12\x34\n\x07\x44\x65stroy\x12\x0f.client.Request\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='client.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_token', full_name='client.Request.client_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='client.Request.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_data', full_name='client.Request.request_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=125,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='client.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_data', full_name='client.Response.response_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=160,
)


_UPFILESLISTREQUEST = _descriptor.Descriptor(
  name='UpFilesListRequest',
  full_name='client.UpFilesListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=182,
)


_UPFILESRETRIEVEREQUEST = _descriptor.Descriptor(
  name='UpFilesRetrieveRequest',
  full_name='client.UpFilesRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='client.UpFilesRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['UpFilesListRequest'] = _UPFILESLISTREQUEST
DESCRIPTOR.message_types_by_name['UpFilesRetrieveRequest'] = _UPFILESRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:client.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:client.Response)
  })
_sym_db.RegisterMessage(Response)

UpFilesListRequest = _reflection.GeneratedProtocolMessageType('UpFilesListRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPFILESLISTREQUEST,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:client.UpFilesListRequest)
  })
_sym_db.RegisterMessage(UpFilesListRequest)

UpFilesRetrieveRequest = _reflection.GeneratedProtocolMessageType('UpFilesRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPFILESRETRIEVEREQUEST,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:client.UpFilesRetrieveRequest)
  })
_sym_db.RegisterMessage(UpFilesRetrieveRequest)



_UPFILESCONTROLLER = _descriptor.ServiceDescriptor(
  name='UpFilesController',
  full_name='client.UpFilesController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=223,
  serialized_end=514,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='client.UpFilesController.List',
    index=0,
    containing_service=None,
    input_type=_UPFILESLISTREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='client.UpFilesController.Create',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='client.UpFilesController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_UPFILESRETRIEVEREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='client.UpFilesController.Update',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='client.UpFilesController.Destroy',
    index=4,
    containing_service=None,
    input_type=_REQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPFILESCONTROLLER)

DESCRIPTOR.services_by_name['UpFilesController'] = _UPFILESCONTROLLER

# @@protoc_insertion_point(module_scope)
